name: VoteforDay
main: za.net.quantumsicarius.voteforday.VoteforDay
version: 1.0
depend: [Spout]
authors: [Quantum-Sicarius,Guy_de_Siguro]
commands:
   voteforday:
      description: Start a new vote.
      usage: /<command>
   vote:
      description: Place your vote.
      usage: /<command> <y/n>

