name: VoteforDay
main: za.net.quantumsicarius.voteforday.VoteforDay
version: 0.2
depend: [Spout]
commands:
   voteforday:
      description: Start a new vote.
      usage: /<command>
      permission: voteforday.voteforday
      permission-message: You don't have voteforday.voteforday
   vote:
      description: Place your vote.
      usage: /<command> <y/n>
      permission: voteforday.vote
      permission-message: You don't have voteforday.vote
